// swift-tools-version:5.9
import PackageDescription

// YouKey Security SDK — closed-source binary distribution.
// This package wraps the signed YoukeySDK.xcframework; no source ships here.
// Generated by the release pipeline — do not edit by hand.
let package = Package(
    name: "YoukeySDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "YoukeySDK", targets: ["YoukeySDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "YoukeySDK",
            url: "https://dl.cloudsmith.io/basic/youkey/youkey-sdk/raw/versions/2.0.0/YoukeySDK.xcframework.zip",
            checksum: "cde2ab611a4e1d793292bd59f840bc6d6626c6903e5f342ddd75386ec17804dc"
        ),
    ]
)
