// swift-tools-version:5.9
import PackageDescription

// YouKey Security SDK — closed-source binary distribution.
// This package wraps the signed YoukeySDK.xcframework; no source ships here.
// Generated by the release pipeline — do not edit by hand.
let package = Package(
    name: "YoukeySDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "YoukeySDK", targets: ["YoukeySDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "YoukeySDK",
            url: "https://dl.cloudsmith.io/basic/youkey/youkey-sdk/raw/versions/2.1.0/YoukeySDK.xcframework.zip",
            checksum: "bf75f8e4818389f4c523c62ca1dad38b8325510e40da5cd2cd0fc75058d009d9"
        ),
    ]
)
