// swift-tools-version:5.9
import PackageDescription

// YouKey Security SDK — closed-source binary distribution.
// This package wraps the signed YoukeySDK.xcframework; no source ships here.
// Generated by the release pipeline — do not edit by hand.
let package = Package(
    name: "YoukeySDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "YoukeySDK", targets: ["YoukeySDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "YoukeySDK",
            url: "https://dl.cloudsmith.io/basic/youkey/youkey-sdk/raw/versions/1.2.3/YoukeySDK.xcframework.zip",
            checksum: "681d4d06f26f26cd1f1e8f1b7b36b0ba01c753a97fe1b1398c28ba2dbf903261"
        ),
    ]
)
